apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aiops-api-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - aiops

  selector:
    matchLabels:
      app: aiops-api

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s